;; -*- lexical-binding: t; no-byte-compile: t; coding: utf-8 -*-

(defun gcr-ui-date ()
  (interactive)
  (switch-to-buffer "*gcr Dates*")
  (let ((inhibit-read-only t))
    (erase-buffer))
  (remove-overlays)
  (widget-insert "╔═════════════════════════════╗\n")
  (widget-insert "║ Add A Date To The Kill-Ring ║\n")
  (widget-insert "╚═════════════════════════════╝")
  (widget-insert "\n\n")
  (widget-insert "Date: (I)SO, (U)S, US With 4 Digit (Y)ear (with (D)ashes), US In (W)ords.\n\n")
  (widget-insert "Date/Time: (N)o Colons, With (C)olons, (L)og Entry with note, (J)ekyll.\n\n")
  (widget-insert "Time: 24h Clock (H)our:Seconds.\n\n")
  (widget-insert "Org-Mode: (T)oday.\n\n")
  (widget-insert "_q_uit")
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map widget-keymap)
    (define-key map "I" 'gcr-timestamp-datestamp)
    (define-key map "Y" 'gcr-timestamp-datestamp-us-full-year)
    (define-key map "U" 'gcr-timestamp-datestamp-us)
    (define-key map "D" 'gcr-timestamp-datestamp-us-full-year-and-dashes)
    (define-key map "W" 'gcr-timestamp-datestamp-us-words)
    (define-key map "J" 'gcr-timestamp-jekyll)
    (define-key map "N" 'gcr-timestamp-8601-no-colons)
    (define-key map "C" 'gcr-timestamp-8601)
    (define-key map "L" 'gcr-log-entry)
    (define-key map "H" 'gcr-timestamp-hour-seconds)
    (define-key map "T" 'gcr-timestamp-org-datestamp)
    (define-key map "q" 'kill-this-buffer)
    (use-local-map map))
  (widget-setup)
  (goto-char (point-min)))

